//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscortServices.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int Id { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public short CityId { get; set; }
        public string CityName { get; set; }
        public short VoivodeshipId { get; set; }
        public byte VoivodeshipName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public byte Age { get; set; }
        public byte Weight { get; set; }
        public string BustSize { get; set; }
        public bool English { get; set; }
        public bool German { get; set; }
        public bool Russian { get; set; }
        public short Price1h { get; set; }
        public Nullable<short> Price30min { get; set; }
        public Nullable<short> Price15min { get; set; }
        public Nullable<short> PriceAllNight { get; set; }
        public Nullable<byte> OutCallsId { get; set; }
        public Nullable<System.TimeSpan> MonFrom { get; set; }
        public Nullable<System.TimeSpan> MonTo { get; set; }
        public Nullable<System.TimeSpan> TueFrom { get; set; }
        public Nullable<System.TimeSpan> TueTo { get; set; }
        public Nullable<System.TimeSpan> WedFrom { get; set; }
        public Nullable<System.TimeSpan> WedTo { get; set; }
        public Nullable<System.TimeSpan> ThuFrom { get; set; }
        public Nullable<System.TimeSpan> ThuTo { get; set; }
        public Nullable<System.TimeSpan> FriFrom { get; set; }
        public Nullable<System.TimeSpan> FroTo { get; set; }
        public Nullable<System.TimeSpan> SatFrom { get; set; }
        public Nullable<System.TimeSpan> SatTo { get; set; }
        public Nullable<System.TimeSpan> SunFrom { get; set; }
        public Nullable<System.TimeSpan> SunTo { get; set; }
        public string ContentPL { get; set; }
        public string ContentEN { get; set; }
        public string ContentDE { get; set; }
        public string ContentRU { get; set; }
        public string PublicId { get; set; }
    }
}
