export interface IAdvertisement {
    id:number;
    categoryId:number;
    categoryName:string;   
    password: string;
    name: string;
    cityId: number;
    cityName: string;
    voivodeshipId: number;
    voivodeshipName: string;
    address: string;
    email: string;
    telephone: string;
    age: number;
    weight: number;
    height:number;
    breastSize: number;
    isEnglish: boolean;
    isGerman: boolean;
    isRussian: boolean;
    price1h: number;
    price30min: number;
    price15min: number;
    priceAllNight: number;
    outCallsId: number;
    monFrom: string;
    monTo: string;
    tueFrom: string;
    tueTo: string;
    wedFrom: string;
    wedTo: string;
    thuFrom: string;
    thuTo: string;
    friFrom: string;
    froTo: string;
    satFrom: string;
    satTo: string;
    sunFrom: string;
    sunTo: string;
    contentPL: string;
    contentEN: string;
    contentDE: string;
    contentRU: string;
    publicId: string;
    date: Date;
}                 